Development34
plamer777/task_manager pull request #1
Opened 2023-03-28 17:39 UTC by plamer777

Реализованы .env-ci, docker-compose-ci.yaml файлы с подстановкой данных из секретов, реализована сборка образов и автоматический deploy. Проверена работа. По API реализована тестовая ручка http://skyprogramm.site:8000/api/, в то время фронт доступен по маршруту http://skyprogramm.site/auth.

2023-03-28 18:19 UTC, painassasin requested changes

2023-03-28 18:19 UTC, painassasin commented on Dockerfile
> +RUN > .env
Файл `.env` мы в образ не кладем, переменные окружения подключаем в docker-compose

2023-03-28 18:19 UTC, painassasin commented on docker-compose-ci.yaml
> +      - migrations
Тут лучше добавить условие `service_completed_successfully`, чтобы api не запустился раньше миграций

2023-03-28 18:19 UTC, painassasin commented on docker-compose-ci.yaml
> +      - .env:/task_manager/.env
Переменные окружения прокидываем не через `volumes`, а через конструкцию
```yaml
env_file: .env
```
И все переменные прокинутся в образ, как будто каждую добавили через команду export или set(windows)

2023-03-28 18:19 UTC, painassasin commented on docker-compose-ci.yaml
> +    ports:
На сервере порты базы наружу не пробрасываем, как и порты api(выше) - только nginx (front)

2023-03-28 18:19 UTC, painassasin commented on docker-compose.yaml
>  version: "3.9"
Версия docker-compose максимальная 3.8

2023-03-28 18:19 UTC, painassasin commented on frontend/.vscode/extensions.json
> +  "recommendations": ["angular.ng-template"]
Файлы фронта давай либо отдельным PR смержим, либо будем использовать образ  `sermalenk/skypro-front:lesson-34`, чтобы не собирать его каждый раз

2023-03-29 13:55 UTC, painassasin requested changes

2023-03-29 13:55 UTC, painassasin commented on pyproject.toml
> +black = "^23.1.0"
`black` лучше ставить в отдельную группу
```shell
poetry add black --group dev
```
А потом при установке указывать не использовать группу dev
```
poetry install --without dev
```
ведь этот пакет на проде тебе не нужен)

2023-03-29 13:55 UTC, painassasin commented on task_manager/core/admin.py
>  class SiteAdmin(admin.ModelAdmin):
Админку пользователя нужно наледовать от `UserAdmin`, тогда не нужно будет исключать `password` и переопределять метод `save_model`
```python
from django.contrib.auth.admin import UserAdmin
```

2023-03-29 13:55 UTC, painassasin commented on task_manager/task_manager/settings.py
> +    "corsheaders",
Не нужен этот пакет

2023-03-29 14:25 UTC, painassasin approved these changes

2023-03-29 14:32 UTC, plamer777 commented on pyproject.toml
> +black = "^23.1.0"
Спасибо за советы, я поправлю эти моменты, стараюсь постепенно что-то тестировать, чтобы не запутаться совсем.

2023-03-29 17:13 UTC, plamer777 commented
Поправил замечания, но админку оставил как было, хочу попробовать более сложным путем сделать.

2023-03-29 17:14 UTC, merged